[workspace]
members = ["crates/api", "crates/core", "crates/engine", "crates/api"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/oblivisheee/aum-engine"
