[package]
name = "aum-core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
